### ISSUE TITLE
Publishing Library "improvment"

### ISSUE THREAD

**Issue by mohammedelnady** [openmobilemaps/maps-core#41]
Distribute your own Android library through Jitpack or jCenter and Maven Central.

**Comment by mohammedelnady** [comment]
is [this](https://bintray.com/openmobilemaps/openmobilemaps/maps-core) belongs to you ?

**Comment by simonroesch** [comment]
Yes, we will add this to the readme soon.

**Comment by mohammedelnady** [comment]
thanks.

**Comment by maurhofer-ubique** [comment]
With the release 1.2.0, the [Android readme](https://github.com/openmobilemaps/maps-core/blob/main/android/readme.md) has been updated to include this reference.
