### ISSUE TITLE
iOS memory leak

### ISSUE THREAD

**Issue by FabioMartignoni89** [openmobilemaps/maps-core#56]
Hi there.
When I deinit the enclosing view controller the memory is not being deallocated. Any idea?

**Comment by stmitt** [comment]
Thanks for the feedback @FabioMartignoni89, 
#57 addresses this issue and will be included in the next release of the SDK.

**Comment by stmitt** [comment]
@FabioMartignoni89  The iOS retain cycle issue was resolved with release 1.3.0. Please let me know if this fixes the issue for you.

**Comment by FabioMartignoni89** [comment]
@stmitt Thank you very much for addressing the issue. 
I just checked 1.3.0 and found that a part of the allocated memory is now released but another part is still retained.

**Comment by FabioMartignoni89** [comment]
Hi stmitt,
great work! 

I tested the 1.3.1 version. 

The memory is being allocated the first time the map is opened, after then, is not allocated again at every successive instance like happened before. 

The memory allocated with the first map instance is never deallocated, but I suppose that is kept for successive usages.
Let me know if that is the intended behaviour. In that case, I can confirm that the issue is resolved.

Thanks a lot.

BR,
Fabio

**Comment by stmitt** [comment]
Hi, @FabioMartignoni89 I looked into this and the initial memory allocation is due to the in-memory caching of network requests.
